version: "3.8"
services:
  mysql_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: user_mgmt
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      DATABASE_URL: mysql://root:root_password@mysql_db:3306/user_mgmt
      JWT_SECRET: my_jwt_sceret

volumes:
  db_data:
